stages:
- name: Build image and push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.cn-hangzhou.aliyuncs.com/wanghaiqing/devops-frontend:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
