stages:
- name: Build image and push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 118.24.103.71:30020/root/devops-frontend:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 118.24.103.71:30020
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
